### ISSUE TITLE
List of project milestones

### ISSUE THREAD

**Issue by benthestatistician** [jghekas/KYhealth#1]
As @jghekas and I discussed, I suggest adding a list of milestones to this project's root directory README.md, where it'll be visible immediately to anyone who checks in with the project. E.g., 
- [x] Obtain restricted data sets
- [x] Assessment of PS models based on restricted data only
- [x] Merge restricted data with current AHRF 
- [x]  Obtain historical AHRF files, for use as baseline data in PS models
- [ ]  PS stratification and/or matching for KY, first pass
- [ ]  Collaborator feedback on PS and post-matching analysis options for KY 
- [ ] ...

(Julie, if you're uncomfortable with having that exposed to the world, I can hook you up with a private repository. But migrating your work over to there would take a bit of doing, so in the interests of minimizing distractions I'd suggest keeping this all here if you can bear it.)

**Comment by benthestatistician** [comment]
Looks good, Julie! Closing this issue.
